# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(464, 474)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(464, 474))
        mainWindow.setMaximumSize(QtCore.QSize(464, 474))
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupView = QtWidgets.QGroupBox(self.centralwidget)
        self.groupView.setGeometry(QtCore.QRect(9, 9, 431, 141))
        self.groupView.setObjectName("groupView")
        self.label_select = QtWidgets.QLabel(self.groupView)
        self.label_select.setGeometry(QtCore.QRect(12, 30, 86, 16))
        self.label_select.setObjectName("label_select")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.groupView)
        self.commandLinkButton.setGeometry(QtCore.QRect(340, 100, 81, 31))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.CB_View = QtWidgets.QComboBox(self.groupView)
        self.CB_View.setGeometry(QtCore.QRect(12, 64, 211, 23))
        self.CB_View.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.CB_View.setObjectName("CB_View")
        self.groupAdd = QtWidgets.QGroupBox(self.centralwidget)
        self.groupAdd.setGeometry(QtCore.QRect(10, 150, 441, 123))
        self.groupAdd.setObjectName("groupAdd")
        self.gridLayout = QtWidgets.QGridLayout(self.groupAdd)
        self.gridLayout.setObjectName("gridLayout")
        self.label_AddEnterServ = QtWidgets.QLabel(self.groupAdd)
        self.label_AddEnterServ.setObjectName("label_AddEnterServ")
        self.gridLayout.addWidget(self.label_AddEnterServ, 0, 0, 1, 1)
        self.LE_AddServ = QtWidgets.QLineEdit(self.groupAdd)
        self.LE_AddServ.setObjectName("LE_AddServ")
        self.gridLayout.addWidget(self.LE_AddServ, 0, 1, 1, 1)
        self.label_AddUser = QtWidgets.QLabel(self.groupAdd)
        self.label_AddUser.setObjectName("label_AddUser")
        self.gridLayout.addWidget(self.label_AddUser, 1, 0, 1, 1)
        self.LE_AddUser = QtWidgets.QLineEdit(self.groupAdd)
        self.LE_AddUser.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.LE_AddUser.setObjectName("LE_AddUser")
        self.gridLayout.addWidget(self.LE_AddUser, 1, 1, 1, 1)
        self.btn_AddNew = QtWidgets.QPushButton(self.groupAdd)
        self.btn_AddNew.setObjectName("btn_AddNew")
        self.gridLayout.addWidget(self.btn_AddNew, 2, 2, 1, 1)
        self.LE_AddPass = QtWidgets.QLineEdit(self.groupAdd)
        self.LE_AddPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LE_AddPass.setObjectName("LE_AddPass")
        self.gridLayout.addWidget(self.LE_AddPass, 2, 1, 1, 1)
        self.label_AddEnterPass = QtWidgets.QLabel(self.groupAdd)
        self.label_AddEnterPass.setObjectName("label_AddEnterPass")
        self.gridLayout.addWidget(self.label_AddEnterPass, 2, 0, 1, 1)
        self.groupDelete = QtWidgets.QGroupBox(self.centralwidget)
        self.groupDelete.setGeometry(QtCore.QRect(10, 290, 441, 141))
        self.groupDelete.setFlat(False)
        self.groupDelete.setObjectName("groupDelete")
        self.labelDlt_EnterServ = QtWidgets.QLabel(self.groupDelete)
        self.labelDlt_EnterServ.setGeometry(QtCore.QRect(12, 30, 125, 16))
        self.labelDlt_EnterServ.setObjectName("labelDlt_EnterServ")
        self.btn_Delete = QtWidgets.QPushButton(self.groupDelete)
        self.btn_Delete.setGeometry(QtCore.QRect(350, 100, 80, 23))
        self.btn_Delete.setObjectName("btn_Delete")
        self.CB_Delete = QtWidgets.QComboBox(self.groupDelete)
        self.CB_Delete.setGeometry(QtCore.QRect(143, 30, 201, 23))
        self.CB_Delete.setObjectName("CB_Delete")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 20))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Password Manager v1.0"))
        self.groupView.setTitle(_translate("mainWindow", "View Password"))
        self.label_select.setText(_translate("mainWindow", "Select Service"))
        self.commandLinkButton.setText(_translate("mainWindow", "Go"))
        self.groupAdd.setTitle(_translate("mainWindow", "Add New Password"))
        self.label_AddEnterServ.setText(_translate("mainWindow", "Enter Service Name"))
        self.label_AddUser.setText(_translate("mainWindow", "Enter Username"))
        self.btn_AddNew.setText(_translate("mainWindow", "Add"))
        self.label_AddEnterPass.setText(_translate("mainWindow", "Enter Password"))
        self.groupDelete.setTitle(_translate("mainWindow", "Delete Password  "))
        self.labelDlt_EnterServ.setText(_translate("mainWindow", "Select Service Name"))
        self.btn_Delete.setText(_translate("mainWindow", "Delete"))

